version: "3.8"

services:
  app:
    build:
      context: .  # The current directory where your Dockerfile is located
      dockerfile: Dockerfile
    container_name: app
    restart: always
    env_file:
      - .env  # Environment variables for your app (make sure it includes DB, Redis, MinIO configs)
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "4000:4000"  # Your app runs on port 4000
    volumes:
      - .:/app  # Mount your current directory for live reloading (optional during dev)
    command: ["bun", "src/index.ts"]  # Start your Bun app

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env  # Load your DB credentials (e.g., POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    env_file:
      - .env  # Include MINIO credentials (e.g., MINIO_ROOT_USER, MINIO_ROOT_PASSWORD)
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # MinIO service port
      - "9001:9001"  # MinIO Console port
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  redis_data:
  minio_data:
